#!/usr/bin/env python3
"""
GSE133398 (SRSF3-KO hepatocytes, Nick Webster lab) — final publication-style figures
for the reviewer rebuttal.

Produces 6 figures (SVG + PNG each), no in-figure titles, no internal jargon
("Option A/B", "stageR") — matches the style of Chikhaoui_Mamgain_MS.pdf's own
figures (descriptive text lives in the companion figure_legends.txt, not on the
plot itself). The splicing volcano is the one exception: it keeps an in-plot
legend (event type = count) since a 7-color scatter needs an on-plot key to be
readable standalone.

Inputs required (all produced earlier in the pipeline):
  - results/normalisation_GSE133398/deseq2_KO_vs_WT.tsv            (gene-level DESeq2)
  - results/normalisation_GSE133398_stageR/deseq2_stageR_KO_vs_WT.tsv  (transcript-level + stageR)
  - results/suppa_GSE133398_2026-07-13/diff/diff_<TYPE>_strict.dpsi.temp.0  (7 files, SRSF3-KO splicing)
  - data/nanopore_suppa/res_<TYPE>.dpsi.temp.0                      (7 files, Nanopore splicing)
  - data/Table3-differential_expressiong_WTvsPerKO.xlsx             (Nanopore DE, perKO_sig sheet)
  - boundary_analysis/data/transcriptome_productivity.gtf           (gene_id -> gene_name map)

Output: results/figures_GSE133398/ (overwrites in place) + figure_legends.txt is
maintained separately (not regenerated by this script — edit by hand if numbers change).

Run from: orthogonal_validation/
    python3 scripts/GSE133398_make_final_figures.py
"""

import os, re, glob
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from adjustText import adjust_text

# =============================================================================
# PATHS (relative to this script's location, so it works from any mount/session)
# =============================================================================
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # .../orthogonal_validation
INTERNSHIP = os.path.dirname(BASE)  # .../Internship
GTF = os.path.join(INTERNSHIP, "boundary_analysis", "data", "transcriptome_productivity.gtf")
OUT = os.path.join(BASE, "results", "figures_GSE133398")
SUPPA_DIR = os.path.join(BASE, "results", "suppa_GSE133398_2026-07-13", "diff")
NAN_SUPPA_DIR = os.path.join(BASE, "data", "nanopore_suppa")
NAN_DE_PATH = os.path.join(BASE, "data", "Table3-differential_expressiong_WTvsPerKO.xlsx")
os.makedirs(OUT, exist_ok=True)

matplotlib.rcParams.update({
    "font.family": "sans-serif", "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"], "font.size": 9,
    "axes.spines.top": False, "axes.spines.right": False, "axes.spines.left": True, "axes.spines.bottom": True,
    "axes.edgecolor": "#AAAAAA", "axes.linewidth": 0.7, "axes.grid": False, "figure.facecolor": "white",
    "axes.facecolor": "white", "xtick.color": "#444444", "ytick.color": "#444444",
    "xtick.labelsize": 7, "ytick.labelsize": 7, "axes.labelsize": 8, "axes.labelcolor": "#222222",
    "xtick.major.size": 3, "ytick.major.size": 3, "xtick.major.width": 0.6, "ytick.major.width": 0.6,
})

ADJ = dict(expand=(2.8, 3.2), force_text=(1.8, 2.8), force_points=(1.3, 1.3),
           arrowprops=dict(arrowstyle="-", color="#888888", lw=0.5, shrinkA=3, shrinkB=3))


def build_gene_map(gtf_path):
    gmap = {}
    with open(gtf_path) as fh:
        for line in fh:
            if "\tgene\t" not in line:
                continue
            gid = re.search(r'gene_id "([^"]+)"', line)
            gname = re.search(r'gene_name "([^"]+)"', line)
            if gid and gname:
                gmap[gid.group(1)] = gname.group(1)
    return gmap


def save_both(fig, name):
    for ext in ["svg", "png"]:
        fig.savefig(os.path.join(OUT, f"{name}.{ext}"), format=ext, bbox_inches="tight",
                    dpi=300 if ext == "png" else None)
    plt.close(fig)
    print(f"  Saved: {name}.svg / .png")


def load_suppa_dir(dirpath, pattern):
    dfs = []
    for f in sorted(glob.glob(os.path.join(dirpath, pattern))):
        base = os.path.basename(f)
        etype = re.sub(r"^(diff_|res_)", "", base)
        etype = re.sub(r"(_strict)?\.dpsi\.temp\.0$", "", etype)
        df = pd.read_csv(f, sep="\t", index_col=0, header=0)
        df.columns = ["dPSI", "pval"]
        df["event_type"] = etype
        df = df.dropna().query("pval > 0")
        dfs.append(df)
    return pd.concat(dfs)


def make_pie(counts, labelA, labelB, path):
    """counts = (only_a, only_b, both). 'Both' gets a short manual leader line
    close to its wedge (no title to dodge anymore, so no need to route it far away)."""
    only_a, only_b, both = counts
    total = only_a + only_b + both
    sizes = [only_a, only_b, both]
    labels = [f"{labelA} only\n({only_a}, {only_a/total*100:.0f}%)",
              f"{labelB} only\n({only_b}, {only_b/total*100:.0f}%)", ""]
    colors = ["#56B4E9", "#009E73", "#E69F00"]
    fig, ax = plt.subplots(figsize=(4.3, 4.3))
    wedges, texts = ax.pie(sizes, labels=labels, colors=colors, startangle=90,
                            labeldistance=1.12, textprops=dict(fontsize=8.5),
                            wedgeprops=dict(edgecolor="white", linewidth=1))
    both_wedge = wedges[2]
    theta = np.deg2rad((both_wedge.theta1 + both_wedge.theta2) / 2)
    x, y = np.cos(theta), np.sin(theta)
    tx, ty = 1.05 + 0.55 * np.cos(theta), y + 0.48
    ha = "left" if x >= 0 else "right"
    ax.annotate(f"Both\n({both}, {both/total*100:.2g}%)", xy=(x, y), xytext=(tx, ty),
                fontsize=8.5, ha=ha, va="bottom",
                arrowprops=dict(arrowstyle="-", color="#888888", lw=0.7, shrinkA=2, shrinkB=2))
    save_both(fig, path)


print("Building gene map from GTF...")
gene_map = build_gene_map(GTF)
print(f"  {len(gene_map)} gene_id -> gene_name pairs")

# =============================================================================
# FIGURE 1 — DE volcano, gene level
# =============================================================================
print("\n=== Figure 1: DE volcano, gene level ===")
de = pd.read_csv(os.path.join(BASE, "results", "normalisation_GSE133398", "deseq2_KO_vs_WT.tsv"),
                  sep="\t", index_col=0)
de.index.name = "gene_id"
de = de.dropna(subset=["log2FoldChange", "padj"])
de = de[de["padj"] > 0]
de["gene_name"] = de.index.map(gene_map)
de["neg_log10_padj"] = -np.log10(de["padj"])
de["category"] = "ns"
de.loc[(de.log2FoldChange > 0.5) & (de.padj < 0.05), "category"] = "up"
de.loc[(de.log2FoldChange < -0.5) & (de.padj < 0.05), "category"] = "down"

fig, ax = plt.subplots(figsize=(4.6, 4.2))
ns_mask = de["category"] == "ns"
ax.scatter(de.loc[ns_mask, "log2FoldChange"], de.loc[ns_mask, "neg_log10_padj"],
           c="#CCCCCC", s=3, alpha=0.3, linewidths=0, zorder=1, rasterized=True)
up_mask = de["category"] == "up"
ax.scatter(de.loc[up_mask, "log2FoldChange"], de.loc[up_mask, "neg_log10_padj"],
           c="#D55E00", s=10, alpha=0.85, linewidths=0, zorder=2)
dn_mask = de["category"] == "down"
ax.scatter(de.loc[dn_mask, "log2FoldChange"], de.loc[dn_mask, "neg_log10_padj"],
           c="#0072B2", s=10, alpha=0.85, linewidths=0, zorder=2)
ax.axvline(0.5, color="#BBBBBB", ls="--", lw=0.7)
ax.axvline(-0.5, color="#BBBBBB", ls="--", lw=0.7)
ax.axhline(-np.log10(0.05), color="#BBBBBB", ls="--", lw=0.7)
top_sig = de[de.category != "ns"].dropna(subset=["gene_name"]).sort_values("padj").head(15)
texts = []
for gid, row in top_sig.iterrows():
    col = "#D55E00" if row.category == "up" else "#0072B2"
    ax.scatter(row.log2FoldChange, row.neg_log10_padj, c=col, s=25, zorder=5, edgecolors="black", linewidths=0.5)
    texts.append(ax.text(row.log2FoldChange, row.neg_log10_padj, row.gene_name, fontsize=6, fontstyle="italic"))
ax.set_ylim(0, de["neg_log10_padj"].max() * 1.12)
adjust_text(texts, ax=ax, **ADJ)
ax.set_xlabel("log₂FC (SRSF3-KO / WT)")
ax.set_ylabel("−log₁₀(padj)")
save_both(fig, "GSE133398_DE_volcano_gene_level")
print(f"  Significant: {(de.category != 'ns').sum()} "
      f"(up={(de.category == 'up').sum()}, down={(de.category == 'down').sum()})")

# =============================================================================
# FIGURE 2 — DE volcano, transcript level (stageR two-stage)
# =============================================================================
print("\n=== Figure 2: DE volcano, transcript level ===")
deb = pd.read_csv(os.path.join(BASE, "results", "normalisation_GSE133398_stageR", "deseq2_stageR_KO_vs_WT.tsv"),
                   sep="\t")
deb = deb.dropna(subset=["log2FoldChange", "padj_gene_stageR"])
deb = deb[deb["padj_gene_stageR"] >= 0]
de_gene = (deb.assign(abslfc=deb["log2FoldChange"].abs())
              .sort_values(["padj_gene_stageR", "abslfc"], ascending=[True, False])
              .drop_duplicates("gene_id").set_index("gene_id"))
de_gene["category"] = "ns"
de_gene.loc[(de_gene.log2FoldChange > 0.5) & (de_gene.padj_gene_stageR < 0.05), "category"] = "up"
de_gene.loc[(de_gene.log2FoldChange < -0.5) & (de_gene.padj_gene_stageR < 0.05), "category"] = "down"

# a handful of genes get an exact-zero padj from stageR (true zero, not just very
# small) -- -log10(0) is infinite, so place those at a fixed ceiling just above
# the highest real value and mark them with a triangle, rather than letting an
# arbitrary percentile cap squash dozens of legitimately-spread-out genes together
true_max_nlp = (-np.log10(de_gene.loc[de_gene.padj_gene_stageR > 0, "padj_gene_stageR"])).max()
ZERO_CEILING = true_max_nlp + 1.0
de_gene["neg_log10_padj"] = np.where(de_gene["padj_gene_stageR"] > 0,
                                      -np.log10(de_gene["padj_gene_stageR"]), ZERO_CEILING)
de_gene["y_plot"] = de_gene["neg_log10_padj"]
de_gene["clipped"] = de_gene["padj_gene_stageR"] == 0

fig, ax = plt.subplots(figsize=(4.6, 4.2))
ns_mask = de_gene["category"] == "ns"
ax.scatter(de_gene.loc[ns_mask, "log2FoldChange"], de_gene.loc[ns_mask, "y_plot"],
           c="#CCCCCC", s=3, alpha=0.3, linewidths=0, zorder=1, rasterized=True)
up_mask = (de_gene["category"] == "up") & ~de_gene["clipped"]
ax.scatter(de_gene.loc[up_mask, "log2FoldChange"], de_gene.loc[up_mask, "y_plot"],
           c="#D55E00", s=10, alpha=0.85, linewidths=0, zorder=2)
up_clip = (de_gene["category"] == "up") & de_gene["clipped"]
if up_clip.any():
    ax.scatter(de_gene.loc[up_clip, "log2FoldChange"], de_gene.loc[up_clip, "y_plot"],
               c="#D55E00", s=14, alpha=0.85, marker="^", linewidths=0, zorder=3)
dn_mask = (de_gene["category"] == "down") & ~de_gene["clipped"]
ax.scatter(de_gene.loc[dn_mask, "log2FoldChange"], de_gene.loc[dn_mask, "y_plot"],
           c="#0072B2", s=10, alpha=0.85, linewidths=0, zorder=2)
dn_clip = (de_gene["category"] == "down") & de_gene["clipped"]
if dn_clip.any():
    ax.scatter(de_gene.loc[dn_clip, "log2FoldChange"], de_gene.loc[dn_clip, "y_plot"],
               c="#0072B2", s=14, alpha=0.85, marker="^", linewidths=0, zorder=3)
ax.axvline(0.5, color="#BBBBBB", ls="--", lw=0.7)
ax.axvline(-0.5, color="#BBBBBB", ls="--", lw=0.7)
ax.axhline(-np.log10(0.05), color="#BBBBBB", ls="--", lw=0.7)
sig_named = de_gene[(de_gene.category != "ns") & (de_gene["gene_name"] != "unannotated")]
# label by log2FC extremes (not padj rank) -- many genes tie at padj=0, so a
# padj-based label pick clusters them all at the same height; picking by fold
# change instead gives natural spread across the x-axis
top_up = sig_named[sig_named.category == "up"].nlargest(6, "log2FoldChange")
top_dn = sig_named[sig_named.category == "down"].nsmallest(6, "log2FoldChange")
top_sig = pd.concat([top_up, top_dn])
texts = []
for gid, row in top_sig.iterrows():
    col = "#D55E00" if row.category == "up" else "#0072B2"
    ax.scatter(row.log2FoldChange, row.y_plot, c=col, s=25, zorder=5, edgecolors="black", linewidths=0.5)
    texts.append(ax.text(row.log2FoldChange, row.y_plot, row.gene_name, fontsize=6, fontstyle="italic"))
ax.set_ylim(0, ZERO_CEILING + 2.4)
adjust_text(texts, ax=ax, **ADJ)
ax.set_xlabel("log₂FC (SRSF3-KO / WT)")
ax.set_ylabel("−log₁₀(padj)")  # deliberately NOT "...stageR gene" -- keep jargon off the axis
save_both(fig, "GSE133398_DE_volcano_transcript_level")
n_sig_genes = (de_gene.category != "ns").sum()
n_sig_tx = ((deb.padj_tx_stageR.notna()) & (deb.padj_tx_stageR < 0.05)).sum()
print(f"  Significant genes (stage 1): {n_sig_genes}; significant transcripts (stage 2): {n_sig_tx}")

# =============================================================================
# FIGURE 3 — splicing dPSI volcano (KEEPS an in-plot legend: event type = count)
# =============================================================================
print("\n=== Figure 3: splicing dPSI volcano ===")
dpsi = load_suppa_dir(SUPPA_DIR, "diff_*_strict.dpsi.temp.0")
dpsi["dPSI"] = -dpsi["dPSI"]  # file is WT-KO -> negate to KO-WT, project convention
dpsi["neg_log10_p"] = -np.log10(dpsi["pval"])
dpsi["sig"] = (dpsi["dPSI"].abs() > 0.1) & (dpsi["pval"] < 0.05)

EVENT_COLORS = {"A3": "#E69F00", "A5": "#56B4E9", "AF": "#009E73", "AL": "#F0E442",
                "MX": "#0072B2", "RI": "#D55E00", "SE": "#CC79A7"}
counts = dpsi[dpsi["sig"]]["event_type"].value_counts()

fig, ax = plt.subplots(figsize=(5.2, 3.8))
ns = dpsi[~dpsi["sig"]]
ax.scatter(ns["dPSI"], ns["neg_log10_p"], c="#CCCCCC", s=4, alpha=0.4, linewidths=0, zorder=1, rasterized=True)
for etype in counts.sort_values(ascending=False).index:
    sub = dpsi[dpsi["sig"] & (dpsi["event_type"] == etype)]
    ax.scatter(sub["dPSI"], sub["neg_log10_p"], c=EVENT_COLORS[etype], s=14, alpha=0.9,
               linewidths=0, zorder=2, label=f"{etype} = {counts[etype]}")
ax.axvline(0.1, color="#BBBBBB", ls="--", lw=0.7)
ax.axvline(-0.1, color="#BBBBBB", ls="--", lw=0.7)
ax.axhline(-np.log10(0.05), color="#BBBBBB", ls="--", lw=0.7)
ax.set_xlabel("dPSI (SRSF3-KO − WT)")
ax.set_ylabel("−log₁₀(p)")
ax.legend(frameon=False, fontsize=6.5, loc="upper left", bbox_to_anchor=(1.02, 1.0),
          markerscale=1.3, handletextpad=0.5, borderaxespad=0)
save_both(fig, "GSE133398_splicing_dPSI_volcano")
print(f"  Significant events: {dpsi['sig'].sum()} / {len(dpsi)}. Breakdown: {dict(counts)}")

# =============================================================================
# Nanopore comparison sets (needed for Figures 4-6)
# =============================================================================
print("\n=== Loading Nanopore comparison data ===")
import openpyxl
wb = openpyxl.load_workbook(NAN_DE_PATH, read_only=True, data_only=True)
ws = wb["perKO_sig"]
rows = list(ws.iter_rows(values_only=True))
nan_de = pd.DataFrame(rows[1:], columns=list(rows[0]))
nan_de_genes = set(nan_de["gene_id"].dropna().unique())

nan_splice = load_suppa_dir(NAN_SUPPA_DIR, "res_*.dpsi.temp.0")
nan_splice_sig = nan_splice[(nan_splice["dPSI"].abs() > 0.1) & (nan_splice["pval"] < 0.05)].copy()
nan_splice_sig["gene_id"] = nan_splice_sig.index.str.split(";").str[0]
nan_splice_genes = set(nan_splice_sig["gene_id"])

srsf3_de_a_genes = set(de[de.category != "ns"].index)
srsf3_de_b_genes = set(de_gene[de_gene.category != "ns"].index)
sig_splice = dpsi[dpsi["sig"]].copy()
sig_splice["gene_id"] = sig_splice.index.str.split(";").str[0]
srsf3_splice_genes = set(sig_splice["gene_id"])

print(f"  Nanopore DE genes: {len(nan_de_genes)}; Nanopore splicing genes: {len(nan_splice_genes)}")
print(f"  SRSF3-KO DE genes -- A: {len(srsf3_de_a_genes)}, B: {len(srsf3_de_b_genes)}; "
      f"splicing genes: {len(srsf3_splice_genes)}")

# =============================================================================
# FIGURE 4/5 — DE overlap with Nanopore, gene level and transcript level
# =============================================================================
print("\n=== Figures 4-5: DE overlap pies ===")
only_nan = len(nan_de_genes - srsf3_de_a_genes)
only_srsf3 = len(srsf3_de_a_genes - nan_de_genes)
both = len(nan_de_genes & srsf3_de_a_genes)
make_pie((only_nan, only_srsf3, both), "Nanopore", "SRSF3-KO", "GSE133398_DE_overlap_Nanopore_gene_level")
print(f"  Gene level: Nanopore only={only_nan}, SRSF3-KO only={only_srsf3}, both={both}")

only_nan = len(nan_de_genes - srsf3_de_b_genes)
only_srsf3 = len(srsf3_de_b_genes - nan_de_genes)
both = len(nan_de_genes & srsf3_de_b_genes)
make_pie((only_nan, only_srsf3, both), "Nanopore", "SRSF3-KO", "GSE133398_DE_overlap_Nanopore_transcript_level")
print(f"  Transcript level: Nanopore only={only_nan}, SRSF3-KO only={only_srsf3}, both={both}")

# =============================================================================
# FIGURE 6 — splicing overlap with Nanopore
# =============================================================================
print("\n=== Figure 6: splicing overlap pie ===")
only_nan = len(nan_splice_genes - srsf3_splice_genes)
only_srsf3 = len(srsf3_splice_genes - nan_splice_genes)
both = len(nan_splice_genes & srsf3_splice_genes)
make_pie((only_nan, only_srsf3, both), "Nanopore", "SRSF3-KO", "GSE133398_splicing_overlap_Nanopore")
print(f"  Nanopore only={only_nan}, SRSF3-KO only={only_srsf3}, both={both}")

print("\n=== ALL 6 FIGURES DONE ===")
print(f"Output folder: {OUT}")
print("Companion legend text (maintained separately, not auto-generated): figure_legends.txt")
